### PR TITLE
fixed assigning waiters

### LINKED ISSUE #141: assignWaiter in the request hander expects orderId but uses orderIds

### PR DESCRIPTION
**Pull request by domberman**
closes #141

### CODE REVIEW

File: server/Data/Stores/OrderStore.ts [hunk 1]
```diff
@@ -33,31 +33,38 @@ export async function removeWaitersFromOrder(
...
+	const order = await getOrder(ordersID);
+	if (order === null) {
 		// Orders existence should have been validated before hand
 		return makeFail(
 			'Something went wrong, could not find requested order',
 			500
 		);
 	}
-	const existedOrders: OrderDAO[] = orders as OrderDAO[];
+	const existedOrders: OrderDAO = order as OrderDAO;
```
Comment (RavidRo) [inline server/Data/Stores/OrderStore.ts:47]: Not used
```suggestion
```

File: server/Logic/IOrder.ts [hunk 2]
```diff
@@ -12,7 +12,7 @@ export interface IOrder {
 	updateWaiterLocation(location: Location): ResponseMsg<void>;
 	updateGuestLocation(location: Location): ResponseMsg<void>;
 
-	assign(waiterId: string): Promise<ResponseMsg<void>>;
+	assign(waiterId: string[]): Promise<ResponseMsg<void>>;
```
Comment (RavidRo) [inline server/Logic/IOrder.ts:15]:
```suggestion
	assign(waiterIds: string[]): Promise<ResponseMsg<void>>;
```

File: server/Logic/Order.ts [hunk 3]
```diff
@@ -96,7 +95,7 @@ export class Order implements IOrder {
 		return makeGood();
 	}
 
-	async assign(_waiterId: string): Promise<ResponseMsg<void>> {
+	async assign(_waiterId: string[]): Promise<ResponseMsg<void>> {
```
Comment (RavidRo) [inline server/Logic/Order.ts:98]:
```suggestion
	async assign(_waiterIds: string[]): Promise<ResponseMsg<void>> {
```

File: server/Logic/WaiterOrder.ts [hunk 4]
```diff
@@ -32,38 +32,24 @@ export async function updateWaiterLocation(
 }
 
 export async function assignWaiter(
```
Comment (RavidRo) [inline server/Logic/WaiterOrder.ts:34]: We should check if some of the waiters is already assigned to the requested order.
If some of them are assigned then we can return an error or proced normally but we dont want to assign again.
I think assigning a waiter twice will result with them getting the same notifications twice.

**Review by RavidRo — CHANGES_REQUESTED** [review]

**Review by RavidRo — APPROVED** [review]
