### PR TITLE
checking if status is a real status

### LINKED ISSUE #140: In update order status, sending a none existent status crashes the server

### PR DESCRIPTION
**Pull request by domberman**
closes #140

### CODE REVIEW

File: server/Interface/DashboardInterface.ts [hunk 1]
```diff
@@ -40,10 +40,23 @@ async function cancelOrderAdmin(
...
+		'assigned',
+		'on the way',
+		'delivered',
+		'canceled',
+	];
+
+	if (!statuses.includes(newStatus)) {
+		return makeFail('There is no such status', 400);
+	}
+	return WaiterOrder.changeOrderStatus(orderID, newStatus as OrderStatus, ID);
```
Comment (RavidRo) [inline server/Interface/DashboardInterface.ts:59]: I think what you are looking for is a TypeGuard

**Review by RavidRo — APPROVED** [review]

**Review by RavidRo — APPROVED** [review]
